---
# Playbook: Creates Prometheus config for ansible-lab-env
- name: Copy Prometheus config
  copy:
    dest: /opt/ansible-lab-env/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          metrics_path: /prometheus/metrics
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'vpsnodeexporter'
          static_configs:
            - targets: ['vpsnodeexporter:9100']

        - job_name: 'dockerscrapercadvisor'
          static_configs:
            - targets: ['dockerscrapercadvisor:8080']
               
        - job_name: 'authelia'
          static_configs:
            - targets: ['authelia:9959']

        - job_name: traefik
          static_configs:
            - targets: ['traefik:9100']
