---
# Playbook: Creates authelia config ansible-lab-env
# Note: This is a sanitized public version.
# Replace placeholder values with your own secure data before use.
- name: Create Authelia configuration.yml
  copy:
    dest: /opt/ansible-lab-env/authelia/configuration.yml
    mode: "0644"
    content: |
      server:
        address: tcp://0.0.0.0:9091/sso


      log:
        level: info

      theme: auto

      session:
        name: authelia_session
        secret: {{ authelia_session_secret }}
        expiration: 1h
        inactivity: 5m
        cookies:
          - name: authelia_session
            domain: {{ project_domain }}
            authelia_url: https://{{ project_domain }}/sso
            default_redirection_url: https://{{ project_domain }}/sso

      telemetry:
        metrics:
          enabled: true
          address: tcp://0.0.0.0:9959/metrics
          buffers:
            read: 4096
            write: 4096
          timeouts:
            read: '5s'
            write: '5s'
            idle: '30s'

      authentication_backend:
        password_reset:
          disable: true
        file:
          path: /config/users_database.yml

      access_control:
        default_policy: deny
        rules:
          - domain: {{ project_domain }}
            resources:
              - "^/sso.*$"
            policy: bypass

          - domain: {{ project_domain }}
            resources:
              - "^/.*$"
            policy: one_factor

      storage:
        encryption_key: {{ authelia_storage_encryption_key }}
        local:
          path: /config/db.sqlite3

      notifier:
        filesystem:
          filename: /config/notification.txt

- name: Generate bcrypt hashes for each user
  set_fact:
    hashed_users: "{{ hashed_users | default([]) + [ {
      'username': item.username,
      'password': (item.password | password_hash('bcrypt')),
      'displayname': item.displayname,
      'groups': item.groups
    } ] }}"
  loop: "{{ authelia_users_raw }}"
  no_log: true

- name: Show absolute path of template on control node
  debug:
    msg: "{{ playbook_dir }}/templates/users_database.yml.j2"


- name: Create Authelia users_database.yml
  template:
    src: templates/users_database.yml.j2
    dest: /opt/ansible-lab-env/authelia/users_database.yml
    mode: "0644"

