---
- name: Create Loki config.yml
  copy:
    dest: /opt/ansible-lab-env/loki/loki-config.yml
    content: |
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095

      common:
        path_prefix: /loki        # required for TSDB v13
        replication_factor: 1     # optional, matches your lifecycler

      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        chunk_retain_period: 30s

      schema_config:
        configs:
          - from: 2025-01-01
            store: tsdb             # TSDB index type
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

      storage_config:
        filesystem:
          directory: /loki/chunks   # TSDB blocks

      limits_config:
        max_entries_limit_per_query: 5000
        max_streams_per_user: 1000
        allow_structured_metadata: true

      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h
