---
# This playbook installs and configures UFW (Uncomplicated Firewall) on a Debian-based system.
- name: Install UFW if not already installed
  apt:
    name: ufw
    state: present

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Deny all other incoming connections
  ufw:
    policy: deny
    direction: incoming

- name: Enable UFW
  ufw:
    state: enabled
    logging: "on"
